### ISSUE TITLE
forceSetMode 

### ISSUE THREAD

**Issue by chankalun** [sourya-sen/ofxSandLine#2]
Hello I am trying to run the "chaining" example and there is this error "No member named 'forceSetMode' in 'ofxSandLine'" that you might wanna check it out :)

Cheers,
Karen

**Comment by sourya-sen** [comment]
Hey @chankalun! I had changed that method to `setMode` instead of `forceSetMode` but had forgotten to update the example, my bad! It's been fixed now, including a more correct way of chaining. You can check it now, it should work fine!
